# Generated by Django 5.2.5 on 2025-08-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisaABIMAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_upload', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('carregando', 'Carregando'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='pendente')),
                ('caminho_resultado', models.CharField(blank=True, max_length=250, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
